//! Embed the Windows resources: the application icon, and the version block.
//!
//! Only Windows has a notion of an icon compiled into the executable. Every
//! other platform gets its icon at runtime from `ViewportBuilder::with_icon`,
//! which this build script has nothing to do with.

fn main() {
    println!("cargo:rerun-if-changed=../../packaging/windows/icon.ico");

    #[cfg(windows)]
    {
        let icon = std::path::Path::new("../../packaging/windows/icon.ico");
        if !icon.is_file() {
            // Not fatal. The icon is generated by `cargo xtask gen-icons`, and a
            // checkout that has not run it should still build a working program.
            println!(
                "cargo:warning=no icon at {}; run `cargo xtask gen-icons`",
                icon.display()
            );
            return;
        }
        let mut res = winresource::WindowsResource::new();
        res.set_icon(&icon.to_string_lossy());
        res.set("ProductName", "Easy Fortran 77");
        res.set("FileDescription", "Easy Fortran 77");
        if let Err(e) = res.compile() {
            // The resource compiler is part of the Windows SDK, and its absence
            // should cost an icon rather than a build.
            println!("cargo:warning=could not embed the icon: {e}");
        }
    }
}
