      PROGRAM SEQNUM                                                    00000010
      INTEGER I                                                         00000020
      I = 7                                                             00000030
      WRITE (*,*) I                                                     00000040
      END                                                               00000050
