//! The application window: every screen, and the state behind them.
//!
//! This file holds no logic of its own. It owns interface state — which screen
//! is showing (`Screen`), which bottom tab (`BottomTab`), whether a toolchain
//! has been found yet (`ToolchainState`), whether a build is running
//! (`BuildState`) — and it turns clicks into calls on `ef-core`.
//!
//! The traffic is one-way. Anything slow happens on a thread and reports back
//! through a `crossbeam_channel::Receiver` that `pump` drains once per frame, so
//! the window keeps drawing while a build, a toolchain probe or an update check
//! is in flight. Nothing here blocks.
//!
//! Two rules, both enforced by `cargo xtask check-hygiene`: this crate may not
//! touch the filesystem (that is `fs_guard`) and may not spawn a process (that
//! is `build::exec`). Every user-visible string goes through `tr!`.

use crate::{markdown, theme};
use crossbeam_channel::Receiver;
use ef_core::build::{
    self, diagnostics::Diagnostic, diagnostics::Severity, BuildEvent, BuildOutcome, BuildPhase,
    ProblemArg,
};
use ef_core::config::{LoadNote, Settings, Store};
use ef_core::fs_guard::FsGuard;
use ef_core::help;
use ef_core::i18n::{self, Lang};
use ef_core::paths::{AppPaths, WorkLayout};
use ef_core::project::{
    suggested_program_file_name, Dialect, FileStatus, LineLength, OptLevel, Program,
};
use ef_core::text;
use ef_core::toolchain::manifest::{Manifest, VerifyReport};
use ef_core::toolchain::Toolchain;
use ef_core::tr;
use ef_core::update;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::{Duration, Instant};

/// Generated by `cargo xtask fetch-toolchain`, embedded here rather than shipped
/// beside the compiler so it cannot be rewritten by whatever rewrote the compiler.
const TOOLCHAIN_MANIFEST: &str = include_str!("../assets/toolchain-manifest.txt");

#[derive(PartialEq, Eq, Clone, Copy)]
enum Screen {
    Programs,
    Help,
    Settings,
}

#[derive(PartialEq, Eq, Clone, Copy)]
enum BottomTab {
    Messages,
    Details,
}

type Discovered = Result<(Toolchain, VerifyReport), String>;

enum ToolchainState {
    Discovering(Receiver<Discovered>),
    Ready {
        tc: Arc<Toolchain>,
        /// Checked once, in the background, before the first build is allowed.
        integrity: VerifyReport,
    },
    Missing(String),
}

/// The result of asking GitHub, or why we could not ask.
type Checked = Result<update::Status, String>;

enum UpdateState {
    /// Never asked this run.
    Idle,
    Checking(Receiver<Checked>),
    Done(Checked),
}

enum BuildState {
    Idle,
    Running {
        rx: Receiver<BuildEvent>,
        cancel: Arc<AtomicBool>,
        phase: BuildPhase,
    },
    Done(Box<BuildOutcome>),
}

pub struct App {
    store: Store,
    settings: Settings,
    programs: Vec<Program>,
    selected: Option<usize>,
    statuses: Vec<FileStatus>,
    lib_statuses: Vec<FileStatus>,

    update: UpdateState,

    screen: Screen,
    bottom: BottomTab,
    help_topic: usize,

    toolchain: ToolchainState,
    build: BuildState,
    /// Where the last successful build was saved, if the user saved it.
    saved_to: Option<PathBuf>,

    diagnostics: Vec<Diagnostic>,
    banner: Option<(String, bool)>,
    build_seq: u64,
    save_due: Option<Instant>,
}

impl App {
    pub fn new(cc: &eframe::CreationContext<'_>) -> Self {
        let fonts = crate::fonts::install(&cc.egui_ctx);
        theme::apply(&cc.egui_ctx);

        let paths = AppPaths::resolve().unwrap_or_else(|_| AppPaths::under(std::env::temp_dir()));
        let mut store = Store::new(paths).expect("the application data directory is not writable");

        // Clear up after sessions that never got to clean up after themselves —
        // a crash, a kill, or a `ef-cli` run, none of which delete their work
        // tree. On a thread of its own because nothing here depends on the
        // answer and the window should not wait on the disk to open.
        {
            let guard = store.guard().clone();
            let work_root = store.paths().work_root();
            let keep = store.paths().session_id().to_string();
            std::thread::spawn(move || {
                let swept = guard.sweep_stale_sessions(
                    &work_root,
                    &keep,
                    std::time::Duration::from_secs(24 * 60 * 60),
                );
                if swept > 0 {
                    tracing::info!("removed {swept} work folder(s) left by earlier sessions");
                }
            });
        }

        let (mut settings, settings_note) = store
            .load_settings()
            .unwrap_or_else(|_| (Settings::default(), LoadNote::Fresh));
        if settings.last_check_utc.is_none() && settings.language == Lang::default() {
            settings.language = Lang::from_locale(sys_locale::get_locale().as_deref());
        }
        // If nothing on this machine can draw Vietnamese, showing it anyway means
        // a screen of empty boxes, which tells the user nothing. egui's built-in font
        // covers ASCII, so English still renders: fall back to it and say why.
        // A real Windows machine always has Segoe UI, so this is a last resort,
        // not an expected path.
        let no_vietnamese_font = fonts.proportional.is_none();
        if no_vietnamese_font {
            settings.language = Lang::En;
        }

        cc.egui_ctx.set_zoom_factor(settings.zoom);

        let (programs, note) = store
            .load_programs()
            .unwrap_or_else(|_| (Vec::new(), LoadNote::Fresh));
        let lang = settings.language;
        // The two files fail independently, so both are reported. Losing the
        // settings and the program list in one startup is rare, but being told
        // about only one of them would leave the user hunting for the other.
        let mut problems: Vec<String> = Vec::new();
        match &settings_note {
            LoadNote::RecoveredFromBackup { corrupt_saved_to } => problems.push(tr!(
                lang,
                "config.settings_recovered",
                path = text::display_path(corrupt_saved_to)
            )),
            LoadNote::StartedEmpty { corrupt_saved_to } => problems.push(tr!(
                lang,
                "config.settings_started_empty",
                path = text::display_path(corrupt_saved_to)
            )),
            LoadNote::TooNew { found } => {
                problems.push(tr!(lang, "config.settings_too_new", found = found))
            }
            _ => {}
        }
        match &note {
            LoadNote::RecoveredFromBackup { corrupt_saved_to } => problems.push(tr!(
                lang,
                "config.recovered",
                path = text::display_path(corrupt_saved_to)
            )),
            LoadNote::StartedEmpty { corrupt_saved_to } => problems.push(tr!(
                lang,
                "config.started_empty",
                path = text::display_path(corrupt_saved_to)
            )),
            LoadNote::TooNew { found } => problems.push(tr!(lang, "config.too_new", found = found)),
            _ => {}
        }
        let mut banner = (!problems.is_empty()).then(|| (problems.join("\n\n"), true));

        if no_vietnamese_font {
            banner = Some((
                "No font on this computer can display Vietnamese, so the interface is in \
                 English. Installing any common font — Segoe UI, Arial, DejaVu Sans — \
                 restores it."
                    .to_string(),
                true,
            ));
        }

        // Probing a compiler takes a moment; never make the user wait at a blank window.
        let (tx, rx) = crossbeam_channel::bounded(1);
        let override_path = settings.toolchain_override.clone();
        std::thread::spawn(move || {
            let r = ef_core::toolchain::discover(override_path.as_deref())
                .map_err(|e| e.to_string())
                .map(|tc| {
                    // Hashing the bundle is part of discovery: nothing should be
                    // built with a compiler we have not checked.
                    let integrity = tc.verify_integrity(&Manifest::parse(TOOLCHAIN_MANIFEST));
                    (tc, integrity)
                });
            let _ = tx.send(r);
        });

        let selected = if programs.is_empty() { None } else { Some(0) };
        let mut app = Self {
            store,
            settings,
            programs,
            selected,
            statuses: Vec::new(),
            lib_statuses: Vec::new(),
            screen: Screen::Programs,
            bottom: BottomTab::Messages,
            help_topic: 0,
            toolchain: ToolchainState::Discovering(rx),
            update: UpdateState::Idle,
            build: BuildState::Idle,
            saved_to: None,
            diagnostics: Vec::new(),
            banner,
            build_seq: 0,
            save_due: None,
        };
        app.refresh_statuses();
        // The setting has said "Check for updates automatically" since before
        // anything checked anything; this is what makes that true. One request,
        // on a background thread, at launch. Failure is silent: someone who
        // opened this to compile a program does not need to hear that GitHub was
        // unreachable.
        if app.settings.check_updates {
            app.check_for_updates();
        }
        app
    }

    fn lang(&self) -> Lang {
        self.settings.language
    }

    fn program(&self) -> Option<&Program> {
        self.selected.and_then(|i| self.programs.get(i))
    }

    fn program_mut(&mut self) -> Option<&mut Program> {
        match self.selected {
            Some(i) => self.programs.get_mut(i),
            None => None,
        }
    }

    fn mark_dirty(&mut self) {
        self.save_due = Some(Instant::now() + Duration::from_millis(750));
    }

    fn save_now(&mut self) {
        if let Err(e) = self.store.save_programs(&self.programs) {
            tracing::error!("could not save programs: {e}");
        }
        if let Err(e) = self.store.save_settings(&self.settings) {
            tracing::error!("could not save settings: {e}");
        }
        self.save_due = None;
    }

    /// The configuration is not a source of truth about what exists on disk.
    fn refresh_statuses(&mut self) {
        let (sources, libraries) = match self.program() {
            Some(p) => (
                p.sources.iter().map(|s| file_status(&s.path)).collect(),
                p.libraries.iter().map(|l| file_status(&l.path)).collect(),
            ),
            None => (Vec::new(), Vec::new()),
        };
        self.statuses = sources;
        self.lib_statuses = libraries;
    }

    fn is_busy(&self) -> bool {
        matches!(self.build, BuildState::Running { .. })
    }

    // -------------------------------------------------------------- actions

    /// Add files to one of the lists, reporting any the model refused.
    fn add_into(&mut self, kind: ListKind, files: Vec<PathBuf>) {
        let mut rejected: Vec<String> = Vec::new();
        if let Some(p) = self.program_mut() {
            for f in files {
                let r = match kind {
                    ListKind::Sources => p.add_source(&f),
                    ListKind::Libraries => p.add_library(&f),
                };
                if let Err(e) = r {
                    rejected.push(e.to_string());
                }
            }
        }
        if !rejected.is_empty() {
            self.banner = Some((rejected.join("\n"), true));
        }
        self.refresh_statuses();
        self.mark_dirty();
    }

    /// Open the file dialog filtered for one of the lists.
    fn pick_into(&mut self, kind: ListKind) {
        let lang = self.lang();
        let k = kind.keys();
        // Both cases are spelled out because the GTK dialog matches a filter's
        // patterns literally, and the user's files are uppercase.
        let exts: Vec<String> = kind
            .extensions()
            .iter()
            .flat_map(|e| [e.to_string(), e.to_uppercase()])
            .collect();
        let dialog = rfd::FileDialog::new()
            .add_filter(i18n::lookup(lang, k.heading), &exts)
            .add_filter(tr!(lang, "common.all_files"), &["*"]);
        if let Some(files) = dialog.pick_files() {
            self.add_into(kind, files);
        }
    }

    fn start_build(&mut self) {
        let ToolchainState::Ready { tc, integrity } = &self.toolchain else {
            return;
        };
        let lang = self.lang();
        // A compiler that failed its integrity check is not used at all. Half of
        // a toolchain produces confusing errors that look like the user's code's fault.
        if !integrity.is_ok() {
            let key = integrity
                .explanation_key()
                .unwrap_or("toolchain.integrity.blocked");
            self.banner = Some((
                format!(
                    "{}\n{}",
                    tr!(lang, "toolchain.integrity.blocked"),
                    i18n::lookup(lang, key)
                ),
                true,
            ));
            return;
        }
        let tc = Arc::clone(tc);
        self.refresh_statuses();

        let Some(program) = self.program().cloned() else {
            return;
        };
        if program.sources.is_empty() {
            self.banner = Some((tr!(lang, "build.no_sources"), true));
            return;
        }
        if self
            .statuses
            .iter()
            .chain(self.lib_statuses.iter())
            .any(|s| !s.is_usable())
        {
            self.banner = Some((tr!(lang, "build.missing_files"), true));
            return;
        }

        self.diagnostics.clear();
        self.banner = None;
        self.saved_to = None;
        self.bottom = BottomTab::Messages;

        self.build_seq += 1;
        let layout = WorkLayout::new(self.store.paths().build_dir(self.build_seq));
        let cancel = Arc::new(AtomicBool::new(false));
        let guard = self.store.guard().clone();
        let rx = build::spawn(guard, tc, layout, program, Arc::clone(&cancel));
        self.build = BuildState::Running {
            rx,
            cancel,
            phase: BuildPhase::Preflight,
        };
        self.save_now();
    }

    fn stop(&mut self) {
        if let BuildState::Running { cancel, .. } = &self.build {
            cancel.store(true, Ordering::SeqCst);
        }
    }

    /// Copy the built program somewhere the user chooses.
    ///
    /// The build happens in a working directory that is cleaned up, so this is
    /// how the user ends up with a program the user can keep.
    fn save_program(&mut self) {
        let BuildState::Done(outcome) = &self.build else {
            return;
        };
        let Some(built) = outcome.exe.clone() else {
            return;
        };
        let lang = self.lang();

        let suggested = self
            .program()
            .map(|p| suggested_program_file_name(&p.name))
            .unwrap_or_else(|| format!("program{}", std::env::consts::EXE_SUFFIX));

        let Some(dest) = rfd::FileDialog::new()
            .set_file_name(&suggested)
            .set_title(tr!(lang, "build.save"))
            .save_file()
        else {
            return;
        };

        if let Err(e) = self.store.guard().export_built_program(&built, &dest) {
            self.banner = Some((tr!(lang, "build.save_failed", reason = e), true));
            return;
        }

        self.banner = Some((
            tr!(lang, "build.saved", path = text::display_path(&dest)),
            false,
        ));
        self.saved_to = Some(dest);
    }

    // -------------------------------------------------------------- updates

    /// Ask GitHub whether there is a newer release, on a thread of its own.
    ///
    /// Never blocks the interface: the window keeps drawing, and the answer
    /// arrives through the same kind of channel the build already uses. If it is
    /// already asking, asking again does nothing.
    fn check_for_updates(&mut self) {
        if matches!(self.update, UpdateState::Checking(_)) {
            return;
        }
        let (tx, rx) = crossbeam_channel::bounded(1);
        std::thread::spawn(move || {
            let answer = update::check(env!("CARGO_PKG_VERSION")).map_err(|e| e.to_string());
            let _ = tx.send(answer);
        });
        self.update = UpdateState::Checking(rx);
    }

    // --------------------------------------------------------------- pumps

    fn pump(&mut self, ctx: &egui::Context) {
        if let UpdateState::Checking(rx) = &self.update {
            if let Ok(answer) = rx.try_recv() {
                self.update = UpdateState::Done(answer);
                ctx.request_repaint();
            }
        }

        // Toolchain discovery
        if let ToolchainState::Discovering(rx) = &self.toolchain {
            if let Ok(result) = rx.try_recv() {
                self.toolchain = match result {
                    Ok((tc, integrity)) => ToolchainState::Ready {
                        tc: Arc::new(tc),
                        integrity,
                    },
                    Err(e) => ToolchainState::Missing(e),
                };
                ctx.request_repaint();
            }
        }

        // Build events
        let mut finished: Option<Box<BuildOutcome>> = None;
        if let BuildState::Running { rx, phase, .. } = &mut self.build {
            while let Ok(ev) = rx.try_recv() {
                match ev {
                    BuildEvent::Phase(p) => *phase = p,
                    BuildEvent::Diagnostics(d) => self.diagnostics.extend(d),
                    BuildEvent::Finished(o) => {
                        finished = Some(o);
                        break;
                    }
                }
            }
        }
        if let Some(outcome) = finished {
            self.diagnostics = outcome.diagnostics.clone();
            self.build = BuildState::Done(outcome);
            ctx.request_repaint();
        }

        // Dropped files
        let dropped: Vec<PathBuf> = ctx.input(|i| {
            i.raw
                .dropped_files
                .iter()
                .map(|f| f.path().to_path_buf())
                .collect()
        });
        if !dropped.is_empty() {
            if self.selected.is_none() {
                self.new_program();
            }
            self.add_into(ListKind::Sources, dropped);
        }

        // Debounced save
        if let Some(due) = self.save_due {
            if Instant::now() >= due {
                self.save_now();
            }
        }

        if self.is_busy() {
            ctx.request_repaint_after(Duration::from_millis(30));
        }
    }

    fn new_program(&mut self) {
        let name = tr!(self.lang(), "programs.new_name");
        self.programs.push(Program::new(name));
        self.selected = Some(self.programs.len() - 1);
        self.refresh_statuses();
        self.mark_dirty();
    }
}

/// Which of the program's two file lists is being drawn.
///
/// Both lists do the same job, so they are drawn by the same code; this names the
/// handful of things that genuinely differ between them.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ListKind {
    Sources,
    Libraries,
}

/// The i18n keys that differ between the two lists.
///
/// The rest — "not found", "up", "down", "locate" — are deliberately shared: they
/// say the same thing about either kind of file, and a second copy would only be
/// a second thing to translate.
struct ListKeys {
    heading: &'static str,
    add: &'static str,
    empty: &'static str,
    remove: &'static str,
    order_hint: &'static str,
    readonly_note: &'static str,
}

impl ListKind {
    fn keys(self) -> ListKeys {
        match self {
            ListKind::Sources => ListKeys {
                heading: "sources.heading",
                add: "sources.add",
                empty: "sources.empty",
                remove: "sources.remove",
                order_hint: "sources.order_hint",
                readonly_note: "sources.readonly_note",
            },
            ListKind::Libraries => ListKeys {
                heading: "libs.heading",
                add: "libs.add",
                empty: "libs.empty",
                remove: "libs.remove",
                order_hint: "libs.order_hint",
                readonly_note: "libs.readonly_note",
            },
        }
    }

    fn extensions(self) -> &'static [&'static str] {
        match self {
            ListKind::Sources => ef_core::fs_guard::FORTRAN_EXTENSIONS,
            ListKind::Libraries => ef_core::build::objfmt::LIBRARY_EXTENSIONS,
        }
    }
}

/// One file's state on disk, as the lists show it.
fn file_status(path: &Path) -> FileStatus {
    match FsGuard::stat_user_source(path) {
        Ok(md) => FileStatus::Present { len: md.len() },
        Err(e) => {
            if !path.exists() {
                FileStatus::Missing
            } else {
                FileStatus::Unreadable(e.to_string())
            }
        }
    }
}

impl eframe::App for App {
    /// State advances here, before any drawing: draining build and program
    /// output, and saving. No ui may be shown from this method.
    fn logic(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        self.pump(ctx);
    }

    fn ui(&mut self, ui: &mut egui::Ui, _frame: &mut eframe::Frame) {
        let lang = self.lang();
        let ctx = ui.ctx().clone();
        let _ = &ctx;

        egui::Panel::top("top").show(ui, |ui| {
            ui.add_space(6.0);
            ui.horizontal(|ui| {
                ui.heading(tr!(lang, "app.title"));
                ui.add_space(12.0);
                ui.selectable_value(
                    &mut self.screen,
                    Screen::Programs,
                    tr!(lang, "nav.programs"),
                );
                ui.selectable_value(&mut self.screen, Screen::Help, tr!(lang, "nav.help"));
                ui.selectable_value(
                    &mut self.screen,
                    Screen::Settings,
                    tr!(lang, "nav.settings"),
                );

                ui.with_layout(
                    egui::Layout::right_to_left(egui::Align::Center),
                    |ui| match &self.toolchain {
                        ToolchainState::Discovering(_) => {
                            ui.spinner();
                            ui.label(tr!(lang, "toolchain.checking"));
                        }
                        ToolchainState::Ready { tc, integrity } if integrity.is_ok() => {
                            ui.label(
                                egui::RichText::new(tr!(
                                    lang,
                                    "toolchain.found",
                                    name = tc.id().display()
                                ))
                                .small()
                                .weak(),
                            );
                        }
                        ToolchainState::Ready { .. } => {
                            ui.colored_label(
                                theme::error_color(ui),
                                tr!(lang, "toolchain.integrity.blocked"),
                            );
                        }
                        ToolchainState::Missing(_) => {
                            ui.colored_label(
                                theme::error_color(ui),
                                tr!(lang, "toolchain.missing"),
                            );
                        }
                    },
                );
            });
            ui.add_space(6.0);
        });

        if let Some((msg, is_error)) = self.banner.clone() {
            egui::Panel::top("banner").show(ui, |ui| {
                ui.add_space(4.0);
                ui.horizontal_wrapped(|ui| {
                    let color = if is_error {
                        theme::error_color(ui)
                    } else {
                        theme::success_color(ui)
                    };
                    ui.colored_label(color, msg);
                    ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                        if ui.button(tr!(lang, "common.close")).clicked() {
                            self.banner = None;
                        }
                    });
                });
                ui.add_space(4.0);
            });
        }

        match self.screen {
            Screen::Programs => self.programs_screen(ui),
            Screen::Help => self.help_screen(ui),
            Screen::Settings => self.settings_screen(ui),
        }
    }

    fn on_exit(&mut self) {
        self.stop();
        self.save_now();
        // Best-effort: this session's scratch tree is no longer needed.
        let session_dir = self.store.paths().session_work_dir();
        let _ = self.store.guard().remove_dir_all(&session_dir);
    }
}

// ------------------------------------------------------------------ screens

impl App {
    fn programs_screen(&mut self, ui: &mut egui::Ui) {
        let lang = self.lang();

        egui::Panel::left("programs")
            .default_size(250.0)
            .show(ui, |ui| {
                ui.add_space(8.0);
                ui.label(egui::RichText::new(tr!(lang, "programs.heading")).strong());
                ui.add_space(4.0);
                if ui
                    .add_sized(
                        [ui.available_width(), theme::BUTTON_HEIGHT],
                        egui::Button::new(tr!(lang, "programs.new")),
                    )
                    .clicked()
                {
                    self.new_program();
                }
                ui.separator();

                if self.programs.is_empty() {
                    ui.add_space(8.0);
                    ui.label(egui::RichText::new(tr!(lang, "programs.empty")).weak());
                }

                egui::ScrollArea::vertical().show(ui, |ui| {
                    let mut select: Option<usize> = None;
                    for (i, p) in self.programs.iter().enumerate() {
                        let label = if p.name.trim().is_empty() {
                            tr!(lang, "programs.new_name")
                        } else {
                            p.name.clone()
                        };
                        let text = format!(
                            "{label}\n{}",
                            tr!(lang, "programs.count", n = p.sources.len())
                        );
                        if ui
                            .selectable_label(self.selected == Some(i), text)
                            .clicked()
                        {
                            select = Some(i);
                        }
                    }
                    if let Some(i) = select {
                        self.selected = Some(i);
                        self.refresh_statuses();
                    }
                });
            });

        egui::Panel::bottom("output")
            .resizable(true)
            .default_size(320.0)
            .min_size(160.0)
            .show(ui, |ui| self.output_panel(ui));

        egui::CentralPanel::default().show(ui, |ui| {
            if self.selected.is_none() {
                ui.add_space(40.0);
                ui.vertical_centered(|ui| {
                    ui.label(egui::RichText::new(tr!(lang, "programs.empty")).size(19.0));
                });
                return;
            }
            egui::ScrollArea::vertical().show(ui, |ui| self.program_detail(ui));
        });
    }

    fn program_detail(&mut self, ui: &mut egui::Ui) {
        let lang = self.lang();
        ui.add_space(6.0);

        // Name
        let mut name = self.program().map(|p| p.name.clone()).unwrap_or_default();
        ui.horizontal(|ui| {
            ui.label(tr!(lang, "programs.name_label"));
            if ui
                .add(egui::TextEdit::singleline(&mut name).desired_width(320.0))
                .changed()
            {
                if let Some(p) = self.program_mut() {
                    p.name = text::nfc(&name);
                    p.touch();
                }
                self.mark_dirty();
            }
            ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                if ui.button(tr!(lang, "common.delete")).clicked() {
                    if let Some(i) = self.selected {
                        self.programs.remove(i);
                        self.selected = if self.programs.is_empty() {
                            None
                        } else {
                            Some(i.saturating_sub(1))
                        };
                        self.refresh_statuses();
                        self.mark_dirty();
                    }
                }
            });
        });

        ui.add_space(10.0);
        ui.separator();

        // The one button that matters.
        let busy = self.is_busy();
        let can_run =
            matches!(&self.toolchain, ToolchainState::Ready { integrity, .. } if integrity.is_ok());
        ui.add_space(8.0);
        ui.horizontal(|ui| {
            if busy {
                if ui
                    .add_sized(
                        [220.0, theme::BIG_BUTTON_HEIGHT],
                        egui::Button::new(egui::RichText::new(tr!(lang, "build.stop")).size(20.0)),
                    )
                    .clicked()
                {
                    self.stop();
                }
                ui.add_space(10.0);
                ui.spinner();
                ui.label(self.phase_text());
            } else {
                let button = egui::Button::new(
                    egui::RichText::new(tr!(lang, "build.run"))
                        .size(21.0)
                        .color(egui::Color32::WHITE),
                )
                .fill(theme::run_button_fill(ui));
                if ui
                    .add_enabled_ui(can_run, |ui| {
                        ui.add_sized([280.0, theme::BIG_BUTTON_HEIGHT], button)
                    })
                    .inner
                    .clicked()
                {
                    self.start_build();
                }
                if let ToolchainState::Missing(detail) = &self.toolchain {
                    ui.vertical(|ui| {
                        ui.colored_label(theme::error_color(ui), tr!(lang, "toolchain.missing"));
                        // A shipped build carries its own compiler, so a missing one
                        // means the installation is damaged -- never that the user should go
                        // and install a toolchain himself. Only a developer build says
                        // that, and only the user ever sees a developer build.
                        if cfg!(debug_assertions) {
                            ui.label(
                                egui::RichText::new(tr!(lang, "toolchain.missing.dev")).small(),
                            );
                        } else {
                            ui.label(
                                egui::RichText::new(tr!(lang, "toolchain.missing.reinstall"))
                                    .small(),
                            );
                            if cfg!(windows) {
                                ui.label(
                                    egui::RichText::new(tr!(lang, "toolchain.missing.antivirus"))
                                        .small()
                                        .weak(),
                                );
                            }
                        }
                        ui.label(egui::RichText::new(detail).small().weak());
                    });
                }
            }
        });
        self.build_result(ui);
        ui.add_space(10.0);
        ui.separator();

        self.file_list(ui, ListKind::Sources);
        ui.add_space(10.0);
        ui.separator();

        self.file_list(ui, ListKind::Libraries);
        ui.add_space(10.0);
        self.options_ui(ui);
    }

    /// What came of the last build, and what to do next.
    fn build_result(&mut self, ui: &mut egui::Ui) {
        let lang = self.lang();
        let BuildState::Done(outcome) = &self.build else {
            return;
        };
        if outcome.cancelled {
            return;
        }

        ui.add_space(6.0);
        if outcome.success {
            ui.horizontal_wrapped(|ui| {
                ui.colored_label(
                    theme::success_color(ui),
                    egui::RichText::new(tr!(lang, "build.succeeded")).strong(),
                );
                if outcome.warnings > 0 {
                    ui.colored_label(
                        theme::warning_color(ui),
                        tr!(lang, "diag.warnings", n = outcome.warnings),
                    );
                }
            });
            ui.label(egui::RichText::new(tr!(lang, "build.succeeded_hint")).small());
            ui.add_space(6.0);
            ui.horizontal(|ui| {
                if ui
                    .add_sized(
                        [240.0, theme::BUTTON_HEIGHT],
                        egui::Button::new(tr!(lang, "build.save")),
                    )
                    .clicked()
                {
                    self.save_program();
                }
                if let Some(saved) = self.saved_to.clone() {
                    if ui.button(tr!(lang, "sources.open_folder")).clicked() {
                        if let Some(dir) = saved.parent() {
                            let _ = opener::open(dir);
                        }
                    }
                    ui.label(
                        egui::RichText::new(text::display_path(&saved))
                            .small()
                            .weak(),
                    );
                }
            });
        } else {
            ui.horizontal_wrapped(|ui| {
                ui.colored_label(
                    theme::error_color(ui),
                    egui::RichText::new(tr!(lang, "build.failed")).strong(),
                );
                if outcome.errors > 0 {
                    ui.colored_label(
                        theme::error_color(ui),
                        tr!(lang, "diag.errors", n = outcome.errors),
                    );
                }
            });
            // A library the user cannot use produces no compiler message at all, so
            // nothing would appear in the messages tab. It is the whole point of
            // checking the format ourselves, and it is said here, in full.
            if let Some(problem) = &outcome.file_problem {
                ui.add_space(8.0);
                ui.vertical(|ui| {
                    ui.set_max_width(680.0);
                    ui.colored_label(
                        theme::error_color(ui),
                        egui::RichText::new(i18n::format(
                            lang,
                            problem.title_key,
                            &[("name", problem.name.as_str())],
                        ))
                        .size(19.0)
                        .strong(),
                    );
                    ui.add_space(4.0);
                    // The key is chosen at build time, so it cannot be a literal.
                    // A `Key` argument is prose in its own right — the name of a
                    // file format — so it is translated before it is substituted,
                    // rather than dropping an English noun into a Vietnamese line.
                    let owned: Vec<(&str, String)> = problem
                        .args
                        .iter()
                        .map(|(k, v)| {
                            let v = match v {
                                ProblemArg::Text(t) => t.clone(),
                                ProblemArg::Key(key) => i18n::lookup(lang, key),
                            };
                            (*k, v)
                        })
                        .collect();
                    let args: Vec<(&str, &str)> =
                        owned.iter().map(|(k, v)| (*k, v.as_str())).collect();
                    ui.label(i18n::format(lang, problem.reason_key, &args));
                });
            } else {
                ui.label(egui::RichText::new(tr!(lang, "build.failed_hint")).small());
                if let Some(detail) = &outcome.internal_error {
                    ui.label(egui::RichText::new(detail).small().weak());
                }
            }
        }
    }

    fn phase_text(&self) -> String {
        let lang = self.lang();
        match &self.build {
            BuildState::Running { phase, .. } => match phase {
                BuildPhase::Preflight => tr!(lang, "build.preflight"),
                BuildPhase::Staging => tr!(lang, "build.staging"),
                BuildPhase::Compiling { done, total, file } => {
                    tr!(
                        lang,
                        "build.compiling",
                        file = file,
                        done = done + 1,
                        total = total
                    )
                }
                BuildPhase::Linking => tr!(lang, "build.linking"),
            },
            _ => String::new(),
        }
    }

    /// One of the program's two file lists.
    ///
    /// Both are the same job — an ordered list of files we only ever read — and
    /// they were written twice. The copies had already begun to drift, so the
    /// varying parts are named here and the ~110 lines of row rendering, ordering
    /// and relocation are written once.
    fn file_list(&mut self, ui: &mut egui::Ui, kind: ListKind) {
        let lang = self.lang();
        let k = kind.keys();

        ui.horizontal(|ui| {
            ui.label(egui::RichText::new(i18n::lookup(lang, k.heading)).strong());
            if ui.button(i18n::lookup(lang, k.add)).clicked() {
                self.pick_into(kind);
            }
        });
        ui.label(
            egui::RichText::new(i18n::lookup(lang, k.order_hint))
                .small()
                .weak(),
        );
        ui.label(
            egui::RichText::new(i18n::lookup(lang, k.readonly_note))
                .small()
                .color(theme::success_color(ui)),
        );
        ui.add_space(4.0);

        let count = self.count(kind);
        if count == 0 {
            ui.label(egui::RichText::new(i18n::lookup(lang, k.empty)).weak());
            return;
        }

        let mut action: Option<(usize, i8)> = None;
        let mut relocate: Option<usize> = None;
        for i in 0..count {
            let (name, path) = self.entry_labels(kind, i);
            let status = self
                .statuses(kind)
                .get(i)
                .cloned()
                .unwrap_or(FileStatus::Missing);

            ui.horizontal(|ui| {
                ui.label(format!("{}.", i + 1));
                ui.vertical(|ui| {
                    match &status {
                        FileStatus::Present { .. } => {
                            ui.label(egui::RichText::new(&name).strong());
                        }
                        FileStatus::Missing => {
                            ui.colored_label(
                                theme::error_color(ui),
                                format!("{name} — {}", tr!(lang, "sources.missing")),
                            );
                        }
                        FileStatus::Unreadable(r) => {
                            ui.colored_label(
                                theme::error_color(ui),
                                tr!(lang, "sources.unreadable", reason = r),
                            );
                        }
                    }
                    ui.label(egui::RichText::new(&path).small().weak());
                });

                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    if ui
                        .button("×")
                        .on_hover_text(i18n::lookup(lang, k.remove))
                        .clicked()
                    {
                        action = Some((i, 0));
                    }
                    if ui.button(tr!(lang, "sources.down")).clicked() {
                        action = Some((i, 1));
                    }
                    if ui.button(tr!(lang, "sources.up")).clicked() {
                        action = Some((i, -1));
                    }
                    if !status.is_usable() && ui.button(tr!(lang, "sources.locate")).clicked() {
                        relocate = Some(i);
                    }
                });
            });
            ui.separator();
        }

        if let Some(i) = relocate {
            if let Some(new) = rfd::FileDialog::new().pick_file() {
                let mut rejected = None;
                if let Some(p) = self.program_mut() {
                    let r = match kind {
                        ListKind::Sources => p.relocate_source(i, &new),
                        ListKind::Libraries => p.relocate_library(i, &new),
                    };
                    if let Err(e) = r {
                        rejected = Some(e.to_string());
                    }
                }
                if let Some(e) = rejected {
                    self.banner = Some((e, true));
                }
                self.refresh_statuses();
                self.mark_dirty();
            }
        }
        if let Some((i, delta)) = action {
            if let Some(p) = self.program_mut() {
                match (kind, delta) {
                    (ListKind::Sources, 0) => p.remove_source(i),
                    (ListKind::Sources, d) => p.move_source(i, d as isize),
                    (ListKind::Libraries, 0) => p.remove_library(i),
                    (ListKind::Libraries, d) => p.move_library(i, d as isize),
                }
            }
            self.refresh_statuses();
            self.mark_dirty();
        }
    }

    fn count(&self, kind: ListKind) -> usize {
        self.program()
            .map(|p| match kind {
                ListKind::Sources => p.sources.len(),
                ListKind::Libraries => p.libraries.len(),
            })
            .unwrap_or(0)
    }

    fn statuses(&self, kind: ListKind) -> &[FileStatus] {
        match kind {
            ListKind::Sources => &self.statuses,
            ListKind::Libraries => &self.lib_statuses,
        }
    }

    fn entry_labels(&self, kind: ListKind, i: usize) -> (String, String) {
        let p = self.program().expect("a list is only drawn with a program");
        match kind {
            ListKind::Sources => (p.sources[i].display_name(), p.sources[i].display_path()),
            ListKind::Libraries => (p.libraries[i].display_name(), p.libraries[i].display_path()),
        }
    }

    fn options_ui(&mut self, ui: &mut egui::Ui) {
        let lang = self.lang();
        let Some(idx) = self.selected else { return };
        let mut changed = false;
        egui::CollapsingHeader::new(tr!(lang, "options.advanced"))
            .default_open(false)
            .show(ui, |ui| {
                let o = &mut self.programs[idx].options;

                ui.horizontal(|ui| {
                    ui.label(tr!(lang, "options.dialect"));
                    changed |= ui
                        .selectable_value(
                            &mut o.dialect,
                            Dialect::Legacy,
                            tr!(lang, "options.dialect.legacy"),
                        )
                        .changed();
                    changed |= ui
                        .selectable_value(
                            &mut o.dialect,
                            Dialect::Standard,
                            tr!(lang, "options.dialect.standard"),
                        )
                        .changed();
                });
                ui.horizontal(|ui| {
                    ui.label(tr!(lang, "options.line_length"));
                    changed |= ui
                        .selectable_value(
                            &mut o.line_length,
                            LineLength::Col72,
                            tr!(lang, "options.line_length.col72"),
                        )
                        .changed();
                    changed |= ui
                        .selectable_value(
                            &mut o.line_length,
                            LineLength::Col132,
                            tr!(lang, "options.line_length.col132"),
                        )
                        .changed();
                    changed |= ui
                        .selectable_value(
                            &mut o.line_length,
                            LineLength::None,
                            tr!(lang, "options.line_length.none"),
                        )
                        .changed();
                });
                changed |= ui
                    .checkbox(&mut o.dec_extensions, tr!(lang, "options.dec"))
                    .changed();
                changed |= ui
                    .checkbox(&mut o.static_storage, tr!(lang, "options.static"))
                    .changed();
                changed |= ui
                    .checkbox(&mut o.d_lines_as_code, tr!(lang, "options.dlines"))
                    .changed();
                changed |= ui
                    .checkbox(&mut o.default_real8, tr!(lang, "options.real8"))
                    .changed();
                changed |= ui
                    .checkbox(&mut o.big_stack, tr!(lang, "options.bigstack"))
                    .changed();
                changed |= ui
                    .checkbox(&mut o.strip_symbols, tr!(lang, "options.strip"))
                    .changed();
                changed |= ui
                    .checkbox(
                        &mut o.keep_window_open,
                        tr!(lang, "options.keep_window_open"),
                    )
                    .on_hover_text(tr!(lang, "options.keep_window_open_hint"))
                    .changed();
                ui.horizontal(|ui| {
                    ui.label(tr!(lang, "options.opt"));
                    for (lvl, name) in [
                        (OptLevel::O0, "-O0"),
                        (OptLevel::O1, "-O1"),
                        (OptLevel::O2, "-O2"),
                    ] {
                        changed |= ui.selectable_value(&mut o.opt_level, lvl, name).changed();
                    }
                });

                let mut extra = o.extra_flags.join(" ");
                ui.horizontal(|ui| {
                    ui.label(tr!(lang, "options.extra"));
                    if ui
                        .add(egui::TextEdit::singleline(&mut extra).desired_width(340.0))
                        .changed()
                    {
                        o.extra_flags = extra.split_whitespace().map(|s| s.to_string()).collect();
                        changed = true;
                    }
                });
            });
        if changed {
            self.programs[idx].touch();
            self.mark_dirty();
        }
    }

    fn output_panel(&mut self, ui: &mut egui::Ui) {
        let lang = self.lang();
        ui.add_space(4.0);
        ui.horizontal(|ui| {
            let errs = self
                .diagnostics
                .iter()
                .filter(|d| d.severity == Severity::Error)
                .count();
            let warns = self
                .diagnostics
                .iter()
                .filter(|d| d.severity == Severity::Warning)
                .count();
            let label = if errs > 0 {
                format!(
                    "{} — {}",
                    tr!(lang, "diag.heading"),
                    tr!(lang, "diag.errors", n = errs)
                )
            } else if warns > 0 {
                format!(
                    "{} — {}",
                    tr!(lang, "diag.heading"),
                    tr!(lang, "diag.warnings", n = warns)
                )
            } else {
                tr!(lang, "diag.heading")
            };
            ui.selectable_value(&mut self.bottom, BottomTab::Messages, label);
            ui.selectable_value(
                &mut self.bottom,
                BottomTab::Details,
                tr!(lang, "diag.details"),
            );

            ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                if ui.button(tr!(lang, "diag.copy")).clicked() {
                    let text = match &self.build {
                        BuildState::Done(o) => o.raw.clone(),
                        _ => String::new(),
                    };
                    ui.ctx().copy_text(text);
                }
            });
        });
        ui.separator();

        match self.bottom {
            BottomTab::Messages => self.messages_ui(ui),
            BottomTab::Details => {
                let raw = match &self.build {
                    BuildState::Done(o) => o.raw.clone(),
                    _ => String::new(),
                };
                egui::ScrollArea::both().show(ui, |ui| {
                    ui.add(
                        egui::TextEdit::multiline(&mut raw.as_str())
                            .font(egui::TextStyle::Monospace)
                            .desired_width(f32::INFINITY),
                    );
                });
            }
        }
    }

    fn messages_ui(&mut self, ui: &mut egui::Ui) {
        let lang = self.lang();
        if self.diagnostics.is_empty() {
            ui.add_space(8.0);
            ui.label(egui::RichText::new(tr!(lang, "diag.none")).weak());
            return;
        }
        egui::ScrollArea::vertical().show(ui, |ui| {
            for d in &self.diagnostics {
                let (color, tag) = match d.severity {
                    Severity::Error => (theme::error_color(ui), "•"),
                    Severity::Warning => (theme::warning_color(ui), "•"),
                    Severity::Note => (ui.visuals().text_color(), "·"),
                };
                ui.horizontal_wrapped(|ui| {
                    ui.colored_label(color, tag);
                    ui.vertical(|ui| {
                        let where_ = match (&d.file, d.line, d.col) {
                            (Some(f), Some(l), Some(c)) => {
                                format!("{f} — {}", tr!(lang, "diag.at_line", line = l, col = c))
                            }
                            (Some(f), _, _) => f.clone(),
                            _ => String::new(),
                        };
                        if !where_.is_empty() {
                            ui.label(egui::RichText::new(where_).strong());
                        }
                        ui.colored_label(color, &d.message);
                        for s in &d.snippet {
                            ui.label(egui::RichText::new(s).monospace().small());
                        }
                    });
                });
                ui.separator();
            }
        });
    }

    fn help_screen(&mut self, ui: &mut egui::Ui) {
        let lang = self.lang();
        egui::Panel::left("help_nav")
            .default_size(230.0)
            .show(ui, |ui| {
                ui.add_space(8.0);
                ui.label(egui::RichText::new(tr!(lang, "help.heading")).strong());
                ui.separator();
                for (i, t) in help::TOPICS.iter().enumerate() {
                    if ui
                        .selectable_label(self.help_topic == i, t.title(lang))
                        .clicked()
                    {
                        self.help_topic = i;
                    }
                }
            });
        egui::CentralPanel::default().show(ui, |ui| {
            egui::ScrollArea::vertical().show(ui, |ui| {
                ui.set_max_width(760.0);
                if let Some(t) = help::TOPICS.get(self.help_topic) {
                    markdown::render(ui, t.body(lang));
                }
                ui.add_space(24.0);
            });
        });
    }

    fn settings_screen(&mut self, ui: &mut egui::Ui) {
        let lang = self.lang();
        egui::CentralPanel::default().show(ui, |ui| {
            ui.add_space(10.0);
            ui.heading(tr!(lang, "settings.heading"));
            ui.add_space(14.0);

            ui.horizontal(|ui| {
                ui.label(tr!(lang, "settings.language"));
                for l in Lang::all() {
                    if ui
                        .selectable_label(self.settings.language == l, l.label())
                        .clicked()
                    {
                        self.settings.language = l;
                        self.mark_dirty();
                    }
                }
            });

            ui.add_space(10.0);
            ui.horizontal(|ui| {
                ui.label(tr!(lang, "settings.zoom"));
                let mut zoom = self.settings.zoom;
                if ui
                    .add(egui::Slider::new(&mut zoom, 0.9..=2.0).step_by(0.05))
                    .changed()
                {
                    self.settings.zoom = zoom;
                    ui.ctx().set_zoom_factor(zoom);
                    self.mark_dirty();
                }
            });

            ui.add_space(16.0);
            ui.separator();
            ui.add_space(10.0);
            ui.label(egui::RichText::new(tr!(lang, "update.heading")).strong());
            ui.label(
                egui::RichText::new(tr!(
                    lang,
                    "update.current",
                    version = env!("CARGO_PKG_VERSION")
                ))
                .small()
                .weak(),
            );
            ui.add_space(6.0);

            ui.horizontal(|ui| {
                let busy = matches!(self.update, UpdateState::Checking(_));
                if ui
                    .add_enabled(!busy, egui::Button::new(tr!(lang, "update.check_now")))
                    .clicked()
                {
                    self.check_for_updates();
                }
                match &self.update {
                    UpdateState::Idle => {}
                    UpdateState::Checking(_) => {
                        ui.spinner();
                        ui.label(tr!(lang, "update.checking"));
                    }
                    UpdateState::Done(Ok(update::Status::UpToDate)) => {
                        ui.colored_label(theme::success_color(ui), tr!(lang, "update.up_to_date"));
                    }
                    UpdateState::Done(Ok(update::Status::Available { version })) => {
                        ui.label(
                            egui::RichText::new(tr!(lang, "update.available", version = version))
                                .strong(),
                        );
                    }
                    UpdateState::Done(Err(e)) => {
                        ui.label(
                            egui::RichText::new(tr!(lang, "update.failed", reason = e))
                                .small()
                                .weak(),
                        );
                    }
                }
            });

            // The download is a separate, deliberate press, and it opens the
            // release page rather than replacing anything behind his back: the
            // installer he runs is the same one he installed with.
            if let UpdateState::Done(Ok(update::Status::Available { .. })) = &self.update {
                ui.add_space(6.0);
                if ui.button(tr!(lang, "update.download")).clicked() {
                    let _ = opener::open_browser(update::releases_page());
                }
                ui.label(
                    egui::RichText::new(tr!(lang, "update.download_hint"))
                        .small()
                        .weak(),
                );
            }

            ui.add_space(10.0);
            if ui
                .checkbox(
                    &mut self.settings.check_updates,
                    tr!(lang, "settings.check_updates"),
                )
                .changed()
            {
                self.mark_dirty();
            }

            ui.add_space(24.0);
            ui.separator();
            ui.label(egui::RichText::new("").small());
            ui.horizontal(|ui| {
                ui.label(
                    egui::RichText::new(text::display_path(self.store.paths().config_dir()))
                        .small()
                        .weak(),
                );
                if ui.small_button(tr!(lang, "settings.open_folder")).clicked() {
                    let _ = opener::open(self.store.paths().config_dir());
                }
            });
        });
    }
}

#[cfg(test)]
mod tests {
    use super::ListKind;
    use ef_core::i18n::{keys, Lang};

    /// The list keys are chosen at run time, so `xtask check-hygiene`'s grep over
    /// literal `tr!` call sites cannot see them. Without this they would be the
    /// only interface strings nothing verified — and a missing Vietnamese entry
    /// does not fail loudly, it silently shows English to someone who does not
    /// read it. Checked against each catalog's own key set for that reason, not
    /// through `lookup`, which falls back to English and would hide it.
    #[test]
    fn every_file_list_key_exists_in_both_catalogs() {
        for kind in [ListKind::Sources, ListKind::Libraries] {
            let k = kind.keys();
            for key in [
                k.heading,
                k.add,
                k.empty,
                k.remove,
                k.order_hint,
                k.readonly_note,
            ] {
                for lang in [Lang::Vi, Lang::En] {
                    assert!(
                        keys(lang).contains(&key),
                        "{key} ({kind:?}) is missing from the {lang:?} catalog"
                    );
                }
            }
        }
    }

    /// Every extension the dialogs offer must be one the rest of the application
    /// agrees is that kind of file.
    #[test]
    fn the_dialog_offers_only_extensions_the_core_knows() {
        assert!(
            ListKind::Sources.extensions().contains(&"for"),
            "legacy sources are .FOR"
        );
        assert!(ListKind::Libraries.extensions().contains(&"lib"));
        for kind in [ListKind::Sources, ListKind::Libraries] {
            for e in kind.extensions() {
                assert_eq!(*e, e.to_ascii_lowercase(), "stored lowercase, cased at use");
            }
        }
    }
}
